### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by angelorc** [citizen-cosmos/Citizen-Cosmos#11]
Hello,
it's Angelo from BitSong.
Could you please add the podcasts license?

I would like to use these podcasts to test our Smart Media Contracts module, where you can subsequently manage the licenses through BitSong

Thanks
Angelo

**Comment by serejandmyself** [comment]
Hey @angelorc 

Thanks for your issue and sorry for the long reply

We have started to research the subject and came to a stand still. On one hand we are the sole creators of the content and the sounds we use are free to use.

On the other hand we do not want to oblige the content under any licensing as this creates legal loopholes which we are trying to avoid. 

What is your expert opinion on the matter?

**Comment by angelorc** [comment]
Hello, sorry for my late reply.
I just asked because could be nice to upload cosmos podcast to bitsong (a cosmos-sdk blokchain based for the music industry)

And I invite you to try the demo by opening a channel https://demo.bitsong.io

This is just a demo connected to a private chain.
