### ISSUE TITLE
Public grants

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Citizen-Cosmos#20]
- [x] Gitcoin @serejandmyself 

1. Create contract for gitcoin
2. Setup page
3. Publish

- [ ] #157

1. Discover other grants
2. Setup page
3. Publish

- [x] [ICF questions](https://github.com/citizen-cosmos/Citizen-Cosmos/issues/55) @Aha203 @serejandmyself

**Comment by serejandmyself** [comment]
https://gitcoin.co/grants/1113/citizen-cosmos-podcast

**Comment by serejandmyself** [comment]
Requires completing

**Comment by VladislavM143** [comment]
Need review

**Comment by serejandmyself** [comment]
- ICF grant: currently irrelevant
- Gitcoin; needs review 
- Patreon: separate task

**Comment by serejandmyself** [comment]
Closed in favor of #157
