### ISSUE TITLE
Help with Content creation and SMM

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Citizen-Cosmos#29]
- [x] Describe @serejandmyself 
- [x] Find @serejandmyself 
- [x] Onboard @serejandmyself 
- [x] Plan roadmap and tasks @serejandmyself @Aha203

**Comment by johnniecosmos** [comment]
Create a Medium page whereby articles/content can be submitted

**Comment by johnniecosmos** [comment]
Also a Reddit designated forum would be good

**Comment by serejandmyself** [comment]
> Create a Medium page whereby articles/content can be submitted

There is a [blog on the website](https://www.citizencosmos.space/articles) that was created to keep the content `ours` =)

**Comment by johnniecosmos** [comment]
How about a reddit channel or a medium channel dedicated to staking. I can get my articles inside that publication for example.

**Comment by serejandmyself** [comment]
I would like to stick to a lesser amount of public media. As in we have a blog on the website we can use to publish all of those.

The general idea behind is very simple:

Its good to share your content with others, but to attract people to your channels, its best to have one single source of truth where that content is published (preferably one you control) and then from it share `snippets` of `teasers` of that content anywhere. This can be your personal medium, FB, reddit, etc. 

There is a dedicated reddit channel for staking ive seen btw. We can share there too. The idea is to lead the people back to you though. So yes, lets publish articles in our blog and then share them on any other SM.

PS. I can easily make you an editor on the site, so you can write the blog posts =)

**Comment by johnniecosmos** [comment]
yes and you can republish my articles if you want!
