### ISSUE TITLE
Althea episode

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Citizen-Cosmos#31]
- [x] Recording
- [x] Editing
- [x] Publishing
- [x] Marketing
- [x] Episode review

**Comment by johnniecosmos** [comment]
The episode has just been shared on three channels of the Secret Network. More to follow.

**Comment by johnniecosmos** [comment]
It will be much harder to share with ecosystems outside ours. I do not know how rules go as far as Reddit and other mediums are concerned too as i believe hyperlinked stuff is getting down by mods on the spot.

**Comment by serejandmyself** [comment]
Yes. That's right. That's why the only way to do this is organically. I.E. If it's an episode about Ethereum, then it's going to an ETH forum / Reddit/ twitter and fining a relevant conversation, where someone can add input

I will describe the idea, not meaning its easy to do... Lets, for the sake of it, take the episode with Tor, about privacy. In the episode we mention privacy gurus and privacy oriented smart contract (among many other things). In an ideal world, I would look around for anywhere that has convo about privacy gurus and where to learn about privacy and say “oh hey, check out Bruce... I heard him being mentioned on a CC episode” (possibly even without the link, unless it feel right to share it).




That's the ideal picture... So this means we can divide marketing of an episode into a few categories:

- Organic listeners (this is our community, who listens to CC regardless of anything)


- Cosmos and episode related chats (TG, Reddit, etc)


- Organic Marketing via the topics discussed in an episode (this is the hardest but the longest in terms of that it can be done forever as long as someone discusses that topic)

- Paid marketing (Google Ads, paid twitter campgains etc)

- General marketing regardless of a particular episode (marking among podcaster communities)
