### ISSUE TITLE
VC episodes

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Citizen-Cosmos#32]
- [x] Locate VC's @johnniecosmos 

1. List of invited VCs:

- [x] Iconomi

- [x] Send out invites @serejandmyself 
- [ ] Record @serejandmyself @Aha203

**Comment by johnniecosmos** [comment]
awaiting answers for the group of investors we talked about in the morning

**Comment by johnniecosmos** [comment]
Done

**Comment by johnniecosmos** [comment]
Another idea would be to contact some from the Akash team, seems like they do some good job with the project. I do not know if you have filled up your spaces for interviews mate.

**Comment by serejandmyself** [comment]
Not yet. Matej said it will take him some time to get an answer

**Comment by johnniecosmos** [comment]
ok i am awaiting your update on this but in all fairness he is the **one** to speak to from what i gathered from comms with Iconomi investors.

**Comment by serejandmyself** [comment]
No answer just yet.

**Comment by johnniecosmos** [comment]
OK buddy just keeping in touch with all open matters here.

**Comment by serejandmyself** [comment]
Closed in favor of re-org
