### ISSUE TITLE
Order TG stickers

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Citizen-Cosmos#33]
- [x] Plan ideas @serejandmyself @johnniecosmos 
- [x] Agree on work @serejandmyself @johnniecosmos 
- [ ] Order @serejandmyself 
- [ ] Announce @serejandmyself @johnniecosmos

**Comment by serejandmyself** [comment]
Need some help with ideas

**Comment by johnniecosmos** [comment]
i do not understand the context here? TG Stickers?

**Comment by serejandmyself** [comment]
Stickers for telegram

**Comment by johnniecosmos** [comment]
One idea is a cosmonaut or cosmonauts in groups being about citizen(s) on cosmos 
Or a spacecraft carrying a small city or a city in space

**Comment by johnniecosmos** [comment]
![image](https://user-images.githubusercontent.com/71050153/98990925-fb752f00-24df-11eb-819e-4de5cda76519.jpeg)

**Comment by johnniecosmos** [comment]
![image](https://user-images.githubusercontent.com/71050153/98991033-1fd10b80-24e0-11eb-8780-87b9be395248.jpeg)

**Comment by johnniecosmos** [comment]
[Idea For stickers](https://www.redbubble.com/i/sticker/Cosmic-Sound-by-buko/38774277.EJUG5#&gid=1&pid=3)

**Comment by johnniecosmos** [comment]
have you done anything in relation to this? shall i look for more ideas?

**Comment by serejandmyself** [comment]
No. We have enough. Will be ordering them )

**Comment by serejandmyself** [comment]
Full re-org. @Aha203 + @serejandmyself have basic designs
