### ISSUE TITLE
Community episodes

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Citizen-Cosmos#35]
- [x] Think of a format @serejandmyself @johnniecosmos 
- [x] [Create a document with the outline of the format](https://github.com/citizen-cosmos/Citizen-Cosmos/blob/master/project/community%20episodes.md) @serejandmyself 
- [x] Invite guests  @johnniecosmos 
- [x] Record @Aha203 @serejandmyself @johnniecosmos 
- [x] Edit @Aha203 
- [x] Publish @serejandmyself @johnniecosmos

**Comment by johnniecosmos** [comment]
Name of Podcast: Denizen Cosmos

**Comment by johnniecosmos** [comment]
Denizen
> a person, animal, or plant that lives or is found in a particular place.

**Comment by johnniecosmos** [comment]
I cannot edit podcasts and will need guidance on recording and all..also i better co-host you da man sir

**Comment by johnniecosmos** [comment]
i think this could be F U N

**Comment by serejandmyself** [comment]
Nice name. The task is for me and you =)

You don't need to edit. I need your help with the format. Shall we get a few people on simultaneously? Although this  is very very very hard to edit. So 5 (together with us) is top I would say. Or shall we just invite one person? What will be the topic of discussion? We can do something like ask the community what they think should discussed? Or decide by ourselfs? Shall we have some special trivia or prizes to go along with it? etc

**Comment by johnniecosmos** [comment]
OK there is another guy i am thinking. Jack Black the meme master

**Comment by johnniecosmos** [comment]
let me put up a list with some nutters..we could get massi too

**Comment by johnniecosmos** [comment]
but i don't know if he will join being a validator and all

**Comment by johnniecosmos** [comment]
Let me know how you want to proceed with this and approximate timeframes for getting them together inviting etc. It will be a bit challenging to coordinate 4-5 people to appear at the same time. Also I will need some guide on what to do to be able to record on my side etc

**Comment by johnniecosmos** [comment]
I was thinking we can try one episode with three guys plus us and see how it goes an example is massi - joe - jazz (iconomi investor) and try coordinate them on the time my self, and then we need to see the format of the chat etc as you say

**Comment by serejandmyself** [comment]
I will make a doc with the description for the episode and the perks

**Comment by johnniecosmos** [comment]
Great Joe, Massi & Jazz have asked around when this will be on.

**Comment by serejandmyself** [comment]
Will have the time this week
