### ISSUE TITLE
Epsiode 18: Starname

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Citizen-Cosmos#40]
- [x] Record
- [x] Edit
- [x] Publish
- [x] Market

**Comment by serejandmyself** [comment]
@johnniecosmos I will push the episode tomorrow morning / tonight and let you know

**Comment by johnniecosmos** [comment]
Hi Serj, is it getting out tomorrow? Please let me know what you require me to do and i will go ahead.

**Comment by serejandmyself** [comment]
Marketing:

1) Paid promotion

- None for now

2) Organic promotion 

- [ ] Sharing by the podcasts guest with his audience
- [ ] Cosmos TG channels
- [ ] Cosmos ecosystem TG channels
- [ ] Hosts private SM
- [ ] CC SM (Twitter, TG, etc)
- [ ] Cosmos Reddit
- [ ] Privacy groups on Twitter
- [ ] Cosmos forum
- [ ] Possible TG groups and chats (web3, etc)
- [ ] Facebook podcast groups

3) General ideas that need more info
- Compliance related discussions
- Voting / identity related

**Comment by johnniecosmos** [comment]
By the way, the podacast has been shared with the IOV community.

**Comment by johnniecosmos** [comment]
**BLOCKCHAIN PRIVACY**

- https://www.reddit.com/r/AllThingsCrypto/
- https://www.reddit.com/r/CryptoCurrencyClassic/
- https://www.reddit.com/r/CryptoCurrency/
- https://www.reddit.com/r/KeepNetwork/
- https://www.reddit.com/r/dimensionchain/
- https://www.reddit.com/r/arpachain/
- https://www.reddit.com/r/codemail/
- https://www.reddit.com/r/ufochain1/
- https://www.reddit.com/user/IoTex_io/
- https://www.reddit.com/r/LightstreamsNetwork/
- https://www.reddit.com/r/FulcrumChain/
- https://www.reddit.com/r/crypticcoin/
- https://www.reddit.com/r/Monero/
- https://www.reddit.com/r/SERO_Official/
- https://www.reddit.com/r/oasislabs/
- https://www.reddit.com/r/Zcash/
- https://www.reddit.com/r/SecretNetwork/
- https://www.reddit.com/r/EnigmaProject/
- https://www.reddit.com/r/cryptomemers/
- https://www.reddit.com/r/cryptomemers/comments/jwpijz/oasis_network_mainnet_is_live_with_over_70/
- https://www.reddit.com/r/CryptoCurrencyClassic/comments/iqxtpk/law_decoded_governments_vs_blockchain_privacy/

**TECHNOLOGY, BLOCKCHAIN VOTING**

- https://www.reddit.com/r/DigitalGrowth/
- https://www.reddit.com/r/WayOfTheBern/
- https://www.reddit.com/r/adChain/
- https://www.reddit.com/r/Bitcoin/
- https://www.reddit.com/r/BlockChain/
- https://www.reddit.com/r/Futurology/
- https://www.reddit.com/r/YangForPresidentHQ/
- https://www.reddit.com/r/technology/
- https://www.reddit.com/r/politics/
- https://www.reddit.com/r/RadiumCore/
- https://www.reddit.com/r/Lobefy/
- https://www.reddit.com/r/sesameseed_community/
- https://www.reddit.com/r/helloicon/
- https://www.reddit.com/r/FollowMyVote/
- https://www.reddit.com/r/inpaycoin/
- https://www.reddit.com/r/GilgameshPlatform/

TECHNOLOGY BLOCKCHAIN IDENTITY

- https://www.reddit.com/r/BlockchainIdentity/
- https://www.reddit.com/r/VelixID/
- https://www.reddit.com/r/ProjectHydro/
- https://www.reddit.com/r/Concordium_Official/
- https://www.reddit.com/r/tokoincommunity/
- https://www.reddit.com/r/OntologyNetwork/
- https://www.reddit.com/r/BloomToken/
- https://www.reddit.com/user/TheKeyVIP/
- https://www.reddit.com/r/Atonomi/
- https://www.reddit.com/r/Idena/
- https://www.reddit.com/r/Authoreon/

**Comment by serejandmyself** [comment]
I will share to some of these during the day if i get the chance and mark them once i did (using my regular reddit account for this)

**Comment by serejandmyself** [comment]
With others of the above list, i guess its about finding an organic conversation to share this episode

**Comment by johnniecosmos** [comment]
Sharing by the podcasts guest with his audience
 Cosmos TG channels **shared**
 Cosmos ecosystem TG channels **shared**
 Hosts private SM
 CC SM (Twitter, TG, etc)
 Cosmos Reddit **have you shared? shall i?**
 Privacy groups on Reddit **sent list**
 Cosmos forum **shall i share?**
 Possible TG groups and chats (web3, etc) TG groups do not allow sharing content unless relevant to the project. **Other coin projects group e.g. / You want me to see if i can find generic telegram groups?**
 Facebook podcast groups **does CC have a facebook account?**

**Comment by serejandmyself** [comment]
Its just a self check list... I put a v there cause i know you shared it on TG channels for example =)

i think the confusion came at the point where you thought it was all your tasks. Some are, some aren't. The idea was to list all the possible variants of sharing the episode content, but its a task for all of us. So if you did any of them, you can simply tick the box to show that you done it. Of course things like " Sharing by the podcasts guest with his audience" or "Hosts private SM" can only be done by the person in question. 

Just like you did with the reddit list. Feel free to tick off the boxes as either share the episode on any of those or where you managed to share a link to it, or in a conversation, etc

The idea is that we will eventually come up with a list of of where we need to share each episode + its sharing on places only relevant to each episode in question. 

- The first one is me asking the guest to share it on their SM. As experience shows, this really boosts the episode. 

- Private SM - private social media. I meant my own FB page, twitter account, etc. 

- Cosmos reddit. If its ticked. Its done =) (so cosmos reddit and forum are done).

- Possible TG groups and chats (web3, etc) : This is more for myself. This is all of the existing TG groups that you dont have a reach out for. Some where Im a mod or its in RU or im just a community member there and can share the episode. So if its ticked - it is. Its done from my side. But once again. If you know TG groups where you can share it. Add them. 

About finding generic TG groups. Thats the idea for each episode and community advocacy here. We both look for TG channels, reddit groups, etc each new episode to see if we can share it there. Sharing doesn't always mean "Hey, here is a link of CC". It could require being an active member in that chat or sharing the episode 1 month later after it came out cause i just saw that it fitted the occasion, etc. 

- Facebook podcast groups: No CC doesn't have one. Im using my own account to share it on various popular FB podcast communities. They are quite lively. But im still new there. So still learning to pull the ropes. Trying to become an active member there and to see if and when its possible to share our work. But again. If you see it ticked. Then i did it. 

I think the best way to help sort it, is for me to add a name tag next to each point on the list (will so so now)

**Comment by johnniecosmos** [comment]
Another idea that could have some benefits would be a promotion via google..just saying here, like google ads although i know we are Cyber haha :)

> About finding generic TG groups. Thats the idea for each episode and community advocacy here. We both look for TG channels, reddit groups, etc each new episode to see if we can share it there. Sharing doesn't always mean "Hey, here is a link of CC". It could require being an active member in that chat or sharing the episode 1 month later after it came out cause i just saw that it fitted the occasion, etc.

I will try build up on my side too, would you like me to start a new fb account for that matter mate?

**Comment by johnniecosmos** [comment]
also some keywords could be worked on the website itself like blockchain privacy on the episode with Tor and Starname...have some specific ones on the website code corresponding to each episode

**Comment by serejandmyself** [comment]
Yep. Need a semantics core. Nothing wrong with using the tools that exist. They are there. You are saying exactly what im thinking

**Comment by johnniecosmos** [comment]
:)

**Comment by serejandmyself** [comment]
About the reddit links. I posted to a few. However a lot of them are closed or like BTC, only about BTC. Also there is a few that are very specific to the projects they are about. 

I guess its more about both of us trying to find an appropriate conversation and linking it. If I succeed I will link it to here to show what I mean
