### ISSUE TITLE
Podcast marketing plan 

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Citizen-Cosmos#44]
- [x] [Episode native marketing guidelines](https://github.com/citizen-cosmos/Citizen-Cosmos/blob/master/project/episode%20workflow.md) @serejandmyself 

- [x] [Content plan for SM](https://github.com/citizen-cosmos/Citizen-Cosmos/blob/master/project/podcast%20content%20plan%20and%20marketing%20roadmap.md) @serejandmyself @johnniecosmos 

1. Create content plan in accordance to episode marketing guidelines
2. Start following the plan

- [x] [Semantics core](https://github.com/citizen-cosmos/Citizen-Cosmos/blob/master/project/semantics.md) @serejandmyself 

1. Create a semantics core that will include podcast and validator unique keywords
2. Start using words in blog posts, SM
3. Use paid ads to promote semantic core

- [ ] R&D podcast marketing companies @serejandmyself 

1. Find and hire a company that can help to promote the product

- [ ] Blog @serejandmyself 

1. Fix previous blog after semantic core is ready
2. Check with content plan

**Comment by johnniecosmos** [comment]
looking forward to this Sergey!

**Comment by VladislavM143** [comment]
+ content plan (workflow);

**Comment by serejandmyself** [comment]
Closed in favor of re-org
