### ISSUE TITLE
Constant and detailed description on all sites

### ISSUE THREAD

**Issue by VladislavM143** [citizen-cosmos/Citizen-Cosmos#84]
- [ ] #149
Descriptions update on all sites where we are presented.
Good layout on all podcast platforms 

- [ ] #150
Conduct a research of podcast aggregators, choose which ones we should be represented on.

- [ ] #151
Register on the main podcast aggregators, add an up-to-date description.

- [ ] #152
Go through the list of all the resources where we are and correct the description for the current one, depending on the category of the resource.

- [ ] #153
Template for: websites, podcast aggregators, news resources.

**Comment by serejandmyself** [comment]
All have separate tasks
