### ISSUE TITLE
Setting up processes

### ISSUE THREAD

**Issue by VladislavM143** [citizen-cosmos/Citizen-Cosmos#85]
- [ ] #121
Create a workflow of work at a conference. Describe everything that we need to prepare before, what promotional materials should be, in what quantity, prepare a back office for clients (who and how to work after preparation). 

- [x] #120
Schedule and add regular meetings to team calendars.

- [ ] #122
Who does what, deadlines. Create job descriptions for each team member, who is responsible for what work, what deadlines. Take instructions from github for example.

**Comment by serejandmyself** [comment]
All have separate tasks. Duplicate
