### ISSUE TITLE
Guests workflow

### ISSUE THREAD

**Issue by VladislavM143** [citizen-cosmos/Citizen-Cosmos#86]
- [ ] #137
Describe in detail the process of working with a guest. 

- [ ] #138
Document (create in advance) a list of potential guests for podcasts. 

- [ ] #139
A large list of basic questions (universal for everyone, divided by categories: vc, engineer, entrepreneur).

- [x] #140
Develop a workflow for communication with a client.

- [ ] #141
Create a reminder for setting up sound for a guest.

- [x] #142
Create a workflow to formulate questions based on the guest's biography.

**Comment by serejandmyself** [comment]
#30

**Comment by serejandmyself** [comment]
All have separate tasks. Duplicate
