### ISSUE TITLE
Basic marketing / SMM

### ISSUE THREAD

**Issue by VladislavM143** [citizen-cosmos/Citizen-Cosmos#88]
- [ ] #119
Find resources that can post us for free, add them to the list, add regularity to the content plan.

- [ ] #118
Research the prices and effectiveness of advertising on Twitter (?), FB, Insta, Telegram. 

- [ ] #117
Carry out a research is Facebook necessary for the podcast ecosystem.

- [ ] #116
Create a page, fill in with data and descriptions, add content for FB to the publication plan, add to the mailing list by podcast groups (free or paid?).

- [ ] #115
Create a page, fill it with data and description, add content for Insta to the publication plan. Add videos and photos from conferences, meetups, meetings to the page. 

- [ ] #114
Create a database of email addresses of users, add users (where to get them?), Think over the motivation to share mail with us. Add a box on the site "" subscribe to news "".
Add a mailing list to the content plan for those who have shared mail (fresh issues, only important news, once every 2-3 days (or less often). 

- [ ] #113
Setting up SEO (keyword search and the like);
Transcripts, google ads, FB, research TA.

**Comment by serejandmyself** [comment]
All have separate tasks. Duplicate
