### ISSUE TITLE
Community guest wish-list 

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Citizen-Cosmos#9]
We are committed to working with our most valuable asset, our listeners, of course!  Let's start an experiment and create a `guest wish-list. Try to keep the wishes somewhat realistic as we are, yet, a small and young project =)

All of the guests will be added to [this list](https://github.com/citizen-cosmos/Citizen-Cosmos/blob/master/community/guest-wish-list.md)

**Simply add a comment to this issue with the name of the guest/s or project you would like to see on the show**

PS. For advanced users: you may fork the [list](https://github.com/citizen-cosmos/Citizen-Cosmos/blob/master/community/guest-wish-list.md) and submit a PR

**Comment by Vgk88** [comment]
Changpeng Zhao (CZ)

**Comment by serejandmyself** [comment]
> Changpeng Zhao (CZ)

`Try to keep the wishes somewhat realistic` ;-)

**Comment by Vgk88** [comment]
> `Try to keep the wishes somewhat realistic` ;-)

Brian Kerr from KAVA

**Comment by serejandmyself** [comment]
> > `Try to keep the wishes somewhat realistic` ;-)
> 
> Brian Kerr from KAVA

Great idea. He is invited already =)

Will remind him of this. Thanks!

**Comment by johnniecosmos** [comment]
Tushar Aggarwal from Persistence One is another one i can get to come here!

**Comment by serejandmyself** [comment]
Great idea. We know each other too. Would be happy to have him on!

**Comment by johnniecosmos** [comment]
he is up for it

**Comment by serejandmyself** [comment]
Can you DM me his email, will send him an invite

**Comment by johnniecosmos** [comment]
on it

**Comment by johnniecosmos** [comment]
Tushar@persistence.one

**Comment by johnniecosmos** [comment]
So we have the puzzle guys, tushar and i have contacted Jae (not logged in TG yet) and two individual investors from Iconomi.

Puzzle guys accepted (i sent their emails, Tushar accepted).

**Comment by serejandmyself** [comment]
Invited them all and updated the [list](https://github.com/citizen-cosmos/Citizen-Cosmos/blob/master/community/guest-wish-list.md)

**Comment by serejandmyself** [comment]
Needs re-org
