### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by VladislavM143** [citizen-cosmos/Citizen-Cosmos#90]
- [ ] #143
Create \ find easy-to-understand analytical tools for calculating key indicators, conduct a research of key indicators for podcasts.

- [ ] #144
Setting up and process of regular monitoring.

- [ ] #145
Setting up and process of regular monitoring.

- [ ] #146
Setting up and process of regular monitoring.

- [ ] #147
Setting up and process of regular monitoring.

- [x] #148
Understand what else is needed and where to monitor it, add to our analytical tools.

**Comment by serejandmyself** [comment]
We need to describe the goals we want to reach with any of these tools before using them

**Comment by serejandmyself** [comment]
All have separate tasks. Duplicate
