### ISSUE TITLE
Citizen ETH podcast

### ISSUE THREAD

**Issue by VladislavM143** [citizen-cosmos/Citizen-Cosmos#96]
- [ ] #154
What projects can we review and discuss, what will be interesting for people, see and record the entire TOP of activities on the blockchain. 

- [ ] #155
Collect in the backlog everyone we may know (or will be introduced to) from the ETH blockchain and who meet our criteria. 

- [x] #156
Get confirmation of the meeting (calculate how many people we need to get started and there was enough content).
Prepare meetings according to the standard workflow.

**Comment by serejandmyself** [comment]
All have separate tasks. Duplicate
